name: create comment on new isssue

on:
  issues:
    types: [opened]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  trace:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      # https://manski.net/articles/github/actions/dump-context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump GitHub Event
      # https://youtu.be/-hVG9z0fCac?si=dAAVltMAbmwyMQBu
      run: echo '${{ toJson(github.event) }}' | jq 
      shell: bash

    - name: Dump GitHub Event 2
      # https://youtu.be/-hVG9z0fCac?si=dAAVltMAbmwyMQBu
      run: echo '${{ toJson(github) }}' | jq --color-output
      shell: bash

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [create-or-update-comment][1]

          [1]: https://github.com/peter-evans/create-or-update-comment
        reactions: '+1'

    - name: Create comment with API
      run: |
        gh api -X POST \
          https://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issue/${ISSUE_NUMBER}
          -f body='
          Comment but from the API call
          '
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}