name: create comment on new isssue

on:
  issues:
    types: [opened]

jobs:
  trace:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      # https://manski.net/articles/github/actions/dump-context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump GitHub Event
      # https://youtu.be/-hVG9z0fCac?si=dAAVltMAbmwyMQBu
      run: echo '${{ toJson(github.event) }}' | jq 
      shell: bash

    - name: Dump GitHub Event 2
      # https://youtu.be/-hVG9z0fCac?si=dAAVltMAbmwyMQBu
      run: echo '${{ toJson(github) }}' | jq --color-output
      shell: bash
