name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      repo_tests:
        description: 'The microptyhon repo used for the test code'
        default: 'https://github.com/micropython/micropython.git@v1.24.1'
        required: true
        type: string

      repo_firmware:
        description: 'The microptyhon repo used to build the firmware'
        default: 'https://github.com/micropython/micropython.git@v1.24.1'
        required: true
        type: string

      aux:
        description: 'Auxiliary arguments to mptest'
        default: '--git-clean --flash-force'
        required: false
        type: string
  
jobs:
  greet:
    runs-on: octoprobe

    steps:
    - name: Send greeting
      run: echo "Hello mptest ${{ inputs.repo_tests }} ${{ inputs.repo_firmware }} ${{ inputs.aux }}"
