name: testbed_micropython Start

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      repo_tests:
        description: 'The microptyhon repo used for the test code'
        default: 'https://github.com/micropython/micropython.git@v1.24.1'
        required: true
        type: string

      repo_firmware:
        description: 'The microptyhon repo used to build the firmware'
        default: 'https://github.com/micropython/micropython.git@v1.24.1'
        required: true
        type: string

      aux:
        description: 'Auxiliary arguments to mptest'
        default: '--git-clean --flash-force'
        required: false
        type: string
  
jobs:
  testbed_micropython:
    # runs-on: octoprobe
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello mptest ${{ inputs.repo_tests }} ${{ inputs.repo_firmware }} ${{ inputs.aux }}"

    - name: Run mptest
      run: |
        . ~/.profile
        mkdir -p testresults
        touch testresults/testresult_${{ github.run_id }}_${{ github.run_number }}.txt
        # mptest test --micropython-tests ${{ inputs.repo_tests }} --firmware-build ${{ inputs.repo_firmware }} ${{ inputs.aux }}
      timeout-minutes: 30.0

    - name: Deploy results to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: testresults