name: test_send_email

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      email:
        description: 'The email address to be used'
        default: 'hans.maerki@gmail.com'
        required: true
        type: string

jobs:
  testrun:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello mptest ${{ inputs.repo_tests }} ${{ inputs.repo_firmware }} ${{ inputs.arguments }}"
      
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_HOST }}
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "Test Email"
        body: "This is a test email sent from the GitHub Actions workflow."
        to: ${{ inputs.email }}
        from: 'buhtig.hans.maerki@ergoinfo.ch'
